version: '3.1'

services:
  server:
    image: server
    container_name: librarian_server
    env_file:
      - .env.prod
    build: ./server/
    ports:
      - "5001:80"
  client:
    image: client
    container_name: librarian_client
    env_file:
      - .env.prod
    build: ./client/
    ports:
      - "5002:3000"
