version: '3.1'

services:
  server:
    image: librarian_server
    container_name: librarian_server
    env_file:
      - ./server/.env.production
    build: ./server/
    ports:
      - "5001:80"
  client:
    image: librarian_client
    container_name: librarian_client
    env_file:
      - ./client/.env.production
    build: ./client/
    ports:
      - "5002:80"
