version: '3.1'

services:
  server:
    image: librarian_server
    container_name: librarian_server
    build: ./server/
    ports:
      - "5001:80"
    env_file:
      - ./server/.env.local
    volumes:
      - ./server/:/app
    restart: unless-stopped
  client:
    image: librarian_server
    container_name: librarian_server
    build: ./client/
    ports:
      - "5002:3000"
    env_file:
      - ./client/.env.local
    volumes:
      - ./client/:/app
      - /app/node_modules # Ignore node_modules
    restart: unless-stopped